# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/golang:1.8

    working_directory: ~/sdk-go

    steps:
      - checkout
      - run:
          name: install make
          command: sudo apt-get update && sudo apt-get -y install gcc make

      - run:
          name: Linting
          command: make lint

      - run:
          name: Testing
          command: make test
